// AdTopia Stripe Payment Links Configuration
// Now uses appConfig.ts as single source of truth

import { APP_CONFIG } from './appConfig';

// Legacy exports for backward compatibility
export const STRIPE_LINKS = {
  // Core Packages
  STARTER: APP_CONFIG.PRICING.STARTER.stripeLink,
  BASIC: APP_CONFIG.PRICING.BASIC.stripeLink,
  PRO: APP_CONFIG.PRICING.PRO.stripeLink,
  ULTIMATE: APP_CONFIG.PRICING.ULTIMATE.stripeLink,
  
  // Add-ons
  TRANSLATION: APP_CONFIG.ADDONS.TRANSLATION.stripeLink,
  DOMAIN_SSL: APP_CONFIG.ADDONS.DOMAIN_SSL.stripeLink,
  EXTRA_CARDS: APP_CONFIG.ADDONS.EXTRA_CARDS.stripeLink,
  ANALYTICS: APP_CONFIG.ADDONS.ANALYTICS.stripeLink,
  SOCIAL_PACK: APP_CONFIG.ADDONS.SOCIAL_PACK.stripeLink,
  
  // Analytics
  ANALYTICS_PRO: APP_CONFIG.ANALYTICS.PRO.stripeLink,
  ANALYTICS_ENTERPRISE: APP_CONFIG.ANALYTICS.ENTERPRISE.stripeLink,
};

// Legacy package exports
export const PACKAGES = {
  STARTER: APP_CONFIG.PRICING.STARTER,
  BASIC: APP_CONFIG.PRICING.BASIC,
  PRO: APP_CONFIG.PRICING.PRO,
  ULTIMATE: APP_CONFIG.PRICING.ULTIMATE,
};

// Redirect URLs for Stripe
export const REDIRECT_URLS = {
  SUCCESS: APP_CONFIG.REDIRECT_URLS.SUCCESS,
  CANCEL: APP_CONFIG.REDIRECT_URLS.CANCEL
};
